apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Heartbeat-workflow
on:
  schedule:
    - cron: 0,6,12,18,24,30,36,42,48,54 * * * *
  push:
    branches:
      - main
  workflow_dispatch:

env:
  ORGANIZATION_URL: '${{ vars.ORGANIZATION_URL }}'
  COMPONENT_ID: '${{ vars.COMPONENT_ID }}'
  WORKFLOW_ID: '${{ vars.WORKFLOW_ID }}'
  BRANCH_ID: '${{ vars.BRANCH_ID }}'
  CLUSTER_ENVIRONMENT: '${{ vars.CLUSTER_ENVIRONMENT }}'
  
jobs:
  build:
    outputs:
      message: ${{ steps.write-message.outputs.message }}
    permissions:
      scm-token-own: read
      scm-token-org: read
      id-token: write
    steps:
      - name: Get source code
        uses: cloudbees-io/checkout@v1
      - name: Setup git credentials
        uses: cloudbees-io/configure-git-global-credentials@v1
      - id: write-message
        name: write-message
        uses: docker://alpine:latest
        run: |
          printf %s $(date -Iseconds) > $CLOUDBEES_OUTPUTS/message
      - id: build
        name: Build using the shared action
        if: ${{ vars.workflow_execution_env == 'production' }}
        uses: docker://golang:1.23.2
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -tags netgo -ldflags '-w -extldflags \"-static\"' -o smoke-tester --buildvcs=0
          
