apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Heartbeat-workflow
on:
  schedule:
    - cron: 0,6,12,18,24,30,36,42,48,54 * * * *
  push:
    branches:
      - main
  workflow_dispatch:

env:
  ORGANIZATION_URL: '${{ vars.ORGANIZATION_URL }}'
  COMPONENT_ID: '${{ vars.COMPONENT_ID }}'
  WORKFLOW_ID: '${{ vars.WORKFLOW_ID }}'
  BRANCH_ID: '${{ vars.BRANCH_ID }}'
  CLUSTER_ENVIRONMENT: '${{ vars.CLUSTER_ENVIRONMENT }}'
  
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
